import React from 'react';

import styles from '../assets/styles/PoliticaDePrivacidade.module.css'
import Menu from 'components/organisms/menu';
import Footer from 'components/organisms/footer';

const PrivacyPolicy = () => {
    return (
        <>
            <Menu isPageTermos={true} />
            <div className={styles.page}>
                <div className={styles.container}>
                    <h1 className={styles.header}>Política de Privacidade da Ensine.me (novembro 2023)</h1>
                    <p className={styles.text}>Bem-vindo à Ensine.me, sua plataforma confiável para conexões educacionais enriquecedoras. Acreditamos firmemente na importância de manter a sua privacidade e segurança. Esta Política de Privacidade foi cuidadosamente elaborada para explicar de forma clara e transparente como suas informações pessoais são coletadas, utilizadas, compartilhadas e protegidas ao utilizar nossos serviços.</p>
                    <p className={styles.text}>Nosso compromisso é não apenas em oferecer uma experiência educacional excepcional, mas também em garantir a integridade e a confidencialidade de suas informações pessoais. Ao usar a Ensine.me, você estará em um ambiente seguro, onde sua privacidade é respeitada e valorizada.</p>

                    <h2 className={styles.sectionTitle}>1. Coleta de Informações</h2>
                    <p className={styles.text}><strong>1.1 Informações de Registro:</strong> Quando você se registra na Ensine.me, coletamos informações essenciais, incluindo, mas não se limitando a, nome, endereço de e-mail, fotografia de perfil, e detalhes financeiros para processamento de pagamentos.</p>
                    <p className={styles.text}><strong>1.2 Dados de Utilização da Plataforma:</strong> Registramos suas interações dentro da plataforma, como frequência de acesso, preferências de cursos, histórico de aulas, e engajamento com conteúdos e usuários.</p>
                    <p className={styles.text}><strong>1.3 Informações de Integração com Terceiros:</strong> Obtemos dados associados à sua conta do Google, abarcando sincronizações de calendário, registros de participação em videoconferências via Google Meet, e outras interações pertinentes com aplicações do Google Workspace.</p>
                    <p className={styles.text}><strong>1.4 Dados de Comunicação:</strong> Coletamos e armazenamos informações trocadas através do serviço de mensagens integrado, utilizando tecnologias como Firebase para análise de conteúdo e segurança da comunicação.</p>
                    <p className={styles.text}><strong>1.5 Monitoramento de Sessões Interativas:</strong> Com o seu consentimento explícito, gravamos sessões de aulas para garantir a qualidade do ensino e para fins de supervisão e segurança, respeitando as legislações de privacidade vigentes.</p>
                    <p className={styles.text}><strong>1.6 Avaliação de Desempenho Educacional:</strong> Analisamos o desempenho acadêmico dos usuários, coletando dados como resultados de avaliações, progresso em cursos, e feedbacks recebidos e enviados.</p>
                    <p className={styles.text}><strong>1.7 Coleta de Dados via Redes Sociais:</strong> Se autorizado, coletamos informações de suas redes sociais que estejam conectadas à plataforma, visando integrar sua experiência de aprendizado com sua presença digital.</p>
                    <p className={styles.text}><strong>1.8 Feedback do Usuário:</strong> Coletamos informações fornecidas voluntariamente em pesquisas, questionários ou outros mecanismos de feedback, com o objetivo de aprimorar continuamente nossos serviços e ofertas educacionais.</p>

                    <h2 className={styles.sectionTitle}>2. Uso das Informações</h2>
                    <p className={styles.text}><strong>2.1 Provisão e Melhoria de Serviços:</strong> Utilizamos as informações coletadas para oferecer e aprimorar nossos serviços educacionais. Isso inclui, mas não se limita a, agendamento de aulas, gerenciamento de conteúdo, manutenção da plataforma e desenvolvimento de novas funcionalidades.</p>
                    <p className={styles.text}><strong>2.2 Comunicação Personalizada:</strong> Empregamos suas informações para enviar comunicações personalizadas, abrangendo atualizações importantes da plataforma, informações sobre novos cursos, ofertas especiais e promoções. Também utilizamos esses dados para responder eficientemente às suas solicitações de suporte e consultas.</p>
                    <p className={styles.text}><strong>2.3 Análise de Interação e Feedback:</strong> Analisamos as interações dos usuários e os feedbacks recebidos para melhorar continuamente a qualidade dos professores, dos cursos oferecidos e da experiência geral na plataforma.</p>
                    <p className={styles.text}><strong>2.4 Estratégias de Marketing e Publicidade:</strong> Utilizamos dados coletados para desenvolver e implementar estratégias de marketing e publicidade direcionadas, incluindo campanhas de remarketing e publicidade em outras plataformas digitais.</p>
                    <p className={styles.text}><strong>2.5 Pesquisa e Desenvolvimento:</strong> Empregamos informações para conduzir pesquisas e análises que apoiam o desenvolvimento de novos produtos, serviços e funcionalidades, visando enriquecer a experiência educacional dos usuários.</p>
                    <p className={styles.text}><strong>2.6 Segurança e Conformidade Legal:</strong> As informações são utilizadas para garantir a segurança da plataforma, prevenir fraudes, cumprir com obrigações legais e regulatórias, e responder a processos legais, como ordens judiciais ou intimações.</p>
                    <p className={styles.text}><strong>2.7 Aprimoramento de Algoritmos e IA:</strong> Utilizamos dados, incluindo interações e padrões de uso, para aprimorar nossos algoritmos e sistemas de inteligência artificial, buscando oferecer uma experiência de aprendizado mais personalizada e eficaz.</p>

                    <h2 className={styles.sectionTitle}>3. Compartilhamento de Informações</h2>
                    <p className={styles.text}><strong>3.1 Respeito ao Consentimento do Usuário:</strong> Mantemos um compromisso rigoroso com sua privacidade. Suas informações pessoais são compartilhadas com terceiros apenas com o seu consentimento expresso, salvo em circunstâncias específicas detalhadas nesta política de privacidade.</p>
                    <p className={styles.text}><strong>3.2 Colaboração com Prestadores de Serviços:</strong> Compartilhamos dados necessários com prestadores de serviços de confiança que desempenham funções essenciais para a operacionalização e melhoria da nossa plataforma, incluindo, mas não se limitando a, processamento de pagamentos, análise de dados, email marketing e hospedagem de serviços.</p>
                    <p className={styles.text}><strong>3.3 Integrações com Plataformas de Terceiros:</strong> Compartilhamos informações específicas com plataformas de terceiros, como Google para a integração de agendas e Google Meet, para facilitar a realização de aulas e reuniões online, sempre em conformidade com as configurações de privacidade do usuário.</p>
                    <p className={styles.text}><strong>3.4 Cumprimento de Obrigações Legais:</strong> Podemos ser obrigados a compartilhar suas informações para cumprir com requisitos legais, responder a processos legais, como ordens judiciais, ou em situações de proteção contra fraudes e outras atividades ilegais.</p>
                    <p className={styles.text}><strong>3.5 Transferências de Negócios:</strong> No caso de uma fusão, aquisição, reestruturação, falência ou outra transferência de negócios, suas informações podem ser transferidas como parte do negócio, sempre respeitando os termos desta política.</p>
                    <p className={styles.text}><strong>3.6 Parcerias Educacionais:</strong> Em algumas circunstâncias, podemos compartilhar informações com instituições educacionais parceiras para oferecer programas conjuntos ou cursos específicos, sempre respeitando a privacidade e o consentimento dos usuários.</p>

                    <h2 className={styles.sectionTitle}>4. Segurança de Dados</h2>
                    <p className={styles.text}><strong>4.1 Medidas de Proteção Avançadas:</strong> Implementamos protocolos de segurança robustos e tecnologias de ponta para proteger suas informações pessoais e sensíveis contra acesso não autorizado, alteração indevida, divulgação não consentida e destruição acidental ou ilícita. Isso inclui, mas não se limita a, criptografia de dados, firewalls, e sistemas de detecção e prevenção de intrusões.</p>
                    <p className={styles.text}><strong>4.2 Responsabilidade Limitada por Conteúdo de Terceiros:</strong> Enquanto facilitamos a integração com plataformas de terceiros, como o Google Meet, para enriquecer a experiência educacional, não temos controle nem assumimos responsabilidade pelos conteúdos ou atividades realizadas nessas plataformas externas.</p>
                    <p className={styles.text}><strong>4.3 Treinamento e Conscientização em Segurança:</strong> Regularmente capacitamos nossa equipe em melhores práticas de segurança de dados e privacidade, assegurando que a manipulação de informações esteja sempre em conformidade com as normas de proteção de dados mais rigorosas.</p>
                    <p className={styles.text}><strong>4.4 Monitoramento e Avaliação Contínua:</strong> Realizamos monitoramento constante e avaliações periódicas de nossos sistemas de segurança para identificar e remediar vulnerabilidades, além de aprimorar continuamente nossas medidas de segurança em resposta a novas ameaças e tecnologias emergentes.</p>
                    <p className={styles.text}><strong>4.5 Gestão de Incidentes de Segurança:</strong> Estabelecemos procedimentos detalhados para a gestão de potenciais incidentes de segurança, incluindo notificação rápida aos usuários e autoridades competentes em caso de violações de segurança que possam afetar suas informações pessoais.</p>

                    <h2 className={styles.sectionTitle}>5. Seus Direitos</h2>
                    <p className={styles.text}><strong>5.1 Direito de Acesso e Autonomia sobre Informações:</strong> Concedemos a você o direito incontestável de acessar suas informações pessoais armazenadas em nossa plataforma. Você pode revisar, corrigir, atualizar ou solicitar a exclusão de seus dados pessoais a qualquer momento, garantindo assim o controle sobre sua privacidade e informações.</p>
                    <p className={styles.text}><strong>5.2 Gerenciamento de Preferências de Comunicação:</strong> Proporcionamos a você a flexibilidade de gerenciar suas preferências de comunicação. Isso inclui a opção de optar por não receber comunicações de marketing, newsletters, ou outras notificações, ajustando suas preferências em sua conta ou através dos links fornecidos em nossos e-mails.</p>
                    <p className={styles.text}><strong>5.3 Direito à Portabilidade de Dados:</strong> Oferecemos a opção de solicitar a transferência de suas informações pessoais para outra entidade, sujeito às condições e limitações legais aplicáveis, garantindo assim a portabilidade de seus dados.</p>
                    <p className={styles.text}><strong>5.4 Direito de Oposição e Restrição de Processamento:</strong> Você tem o direito de se opor ou solicitar a restrição do processamento de suas informações pessoais sob certas condições, especialmente em casos onde a precisão dos dados é contestada ou o processamento é realizado para fins de marketing direto.</p>
                    <p className={styles.text}><strong>5.5 Direito a Notificações de Alterações:</strong> Comprometemo-nos a comunicar qualquer alteração significativa em como utilizamos suas informações pessoais, garantindo que você esteja sempre informado e capaz de exercer seus direitos adequadamente.</p>
                    <p className={styles.text}><strong>5.6 Direito de Retirar o Consentimento:</strong> Você tem o direito de retirar o consentimento para o processamento de suas informações pessoais a qualquer momento, sem afetar a legalidade do processamento anterior à retirada.</p>

                    <h2 className={styles.sectionTitle}>6. Alterações na Política de Privacidade</h2>
                    <p className={styles.text}><strong>6.1 Direito de Modificação:</strong> Nos reservamos o direito de modificar ou atualizar esta política de privacidade a qualquer momento, para refletir mudanças nas nossas práticas de coleta, uso e segurança de dados, ou para estar em conformidade com mudanças legislativas ou regulatórias aplicáveis.</p>
                    <p className={styles.text}><strong>6.2 Notificação de Alterações:</strong> Comprometemo-nos a informar nossos usuários sobre quaisquer mudanças significativas em nossa política de privacidade. As alterações entrarão em vigor imediatamente após sua publicação em nossa plataforma. Encorajamos os usuários a revisarem periodicamente esta política para se manterem atualizados sobre como protegemos suas informações.</p>
                    <p className={styles.text}><strong>6.3 Registro de Versões Anteriores:</strong> Manteremos um registro acessível das versões anteriores de nossa política de privacidade, proporcionando aos usuários a oportunidade de revisar as mudanças ao longo do tempo.</p>
                    <p className={styles.text}><strong>6.4 Consentimento Contínuo:</strong> O uso contínuo de nossa plataforma após quaisquer alterações nesta política será considerado como aceitação dessas mudanças. Se não concordar com os termos atualizados da política, o usuário tem o direito de descontinuar o uso de nossos serviços.</p>
                    <p className={styles.text}><strong>6.5 Consulta Pública e Feedback:</strong> Antes de implementar mudanças significativas, podemos, a nosso critério, disponibilizar rascunhos das alterações propostas para consulta pública, convidando feedback e comentários de nossos usuários. Isso visa promover transparência e engajamento com nossa comunidade, assegurando que as mudanças reflitam as necessidades e preocupações dos usuários.</p>
                    <p className={styles.text}><strong>6.6 Impacto nas Parcerias e Acordos:</strong> Analisaremos o impacto de quaisquer alterações na política em relação a acordos existentes com parceiros e prestadores de serviços, garantindo a continuidade e a conformidade de tais relações sob os novos termos.</p>

                    <h2 className={styles.sectionTitle}>7. Responsabilidade Limitada</h2>
                    <p className={styles.text}><strong>7.1 Relações entre Professores e Alunos:</strong> A Ensine.me não assume responsabilidade legal por quaisquer interações pessoais, acadêmicas ou transações financeiras que ocorram entre professores e alunos fora do escopo funcional da plataforma. Isso inclui, mas não se limita a, interações ou acordos realizados após os encontros agendados através da nossa plataforma.</p>
                    <p className={styles.text}><strong>7.2 Conteúdo Gerado por Usuário:</strong> Não nos responsabilizamos pelo conteúdo gerado pelos usuários, incluindo opiniões, conselhos, declarações ou outro material publicado pelos professores ou alunos. A responsabilidade pelo conteúdo compartilhado é exclusiva do usuário que o publica.</p>
                    <p className={styles.text}><strong>7.3 Serviços de Terceiros:</strong> Qualquer envolvimento com serviços ou plataformas de terceiros, incluindo, mas não se limitando a, Google Meet e serviços integrados, está sujeito às políticas desses serviços, e a Ensine.me não se responsabiliza por práticas de privacidade ou conteúdo de tais serviços.</p>
                    <p className={styles.text}><strong>7.4 Limitação de Responsabilidade Tecnológica:</strong> Enquanto nos esforçamos para manter a plataforma operando de maneira segura e ininterrupta, não garantimos que o funcionamento será sempre livre de erros, interrupções ou será imune a ataques cibernéticos. Consequentemente, a responsabilidade por perdas ou danos decorrentes de tais incidentes será limitada.</p>
                    <p className={styles.text}><strong>7.5 Avaliações e Feedbacks:</strong> As avaliações e feedbacks fornecidos na plataforma são opiniões subjetivas dos usuários e não refletem necessariamente as opiniões ou políticas da Ensine.me. Não nos responsabilizamos por monitorar ou validar tais conteúdos.</p>

                    <h2 className={styles.sectionTitle}>8. Contato</h2>
                    <p className={styles.text}><strong>8.1 Suporte de Política de Privacidade:</strong> Se você tiver dúvidas, preocupações ou necessitar de esclarecimentos sobre esta política de privacidade, não hesite em entrar em contato conosco. Nosso time de suporte está disponível e pode ser contatado através do e-mail <i><strong>suporte@ensineme.org</strong></i>.</p>
                    <p className={styles.text}><strong>8.2 Canais de Comunicação:</strong> Além do e-mail, oferecemos diferentes canais de comunicação para atender às suas necessidades, incluindo suporte telefônico e chat ao vivo em nossa plataforma, para garantir um atendimento eficaz e personalizado.</p>
                    <p className={styles.text}><strong>8.3 Feedback e Sugestões:</strong> Valorizamos o feedback e as sugestões de nossos usuários para aprimorar nossos serviços. Encorajamos você a compartilhar suas ideias e comentários conosco através de nossos canais de comunicação ou diretamente pela seção de feedback em nosso site.</p>
                    <p className={styles.text}><strong>8.4 Atendimento de Reclamações:</strong> Estamos comprometidos em resolver quaisquer reclamações relacionadas à sua privacidade e à coleta e uso de suas informações pessoais. Caso tenha alguma reclamação, entre em contato conosco para que possamos buscar uma solução adequada.</p>
                    <p className={styles.text}><strong>8.5 Informações de Contato:</strong> Para todas as correspondências, nosso endereço de e-mail principal é <i><strong>suporte@ensineme.org</strong></i>. Para suporte telefônico ou outras formas de contato, por favor visite a seção 'Contate-nos' em nosso site para obter as informações atualizadas.</p>

                    <h2 className={styles.sectionTitle}>9. Conclusão</h2>
                    <p className={styles.text}>Ao utilizar a plataforma Ensine.me, você reconhece e concorda expressamente com as práticas de coleta, uso, compartilhamento e proteção de suas informações pessoais conforme descrito nesta Política de Privacidade. Entendemos a importância da sua privacidade e estamos comprometidos em proteger suas informações pessoais com o máximo de cuidado e transparência.</p>
                    <p className={styles.text}>Lembramos que esta política pode sofrer alterações periódicas, e incentivamos os usuários a revisarem frequentemente este documento para se manterem informados sobre como estamos protegendo suas informações. O uso continuado de nossos serviços após tais alterações constitui sua aceitação das políticas revisadas.</p>
                    <p className={styles.text}>Agradecemos por confiar na Ensine.me para suas necessidades educacionais e nos comprometemos a continuar trabalhando para oferecer uma experiência segura, transparente e enriquecedora. Se tiver dúvidas ou preocupações, por favor, entre em contato conosco através dos canais mencionados na seção 'Contato'.</p>
                    <h4 className={styles.text}>Última atualização: 19 de novembro de 2023</h4>                
                </div>
            </div>
            <Footer />
        </>
    );
}

export default PrivacyPolicy;
