import React from "react";
import "../styles/professordash.css"
import CardAula from "../components/CardAula";

function ProfessorDashBoard() {
    return (
        <>
            <div className="contentProfessorDashboard">
                <div className="boxesDashProfessorDashboard">
                    <div className="boxProfessorDashboard">
                        <h1>Aulas Pendentes</h1>
                        <div className="contentListProfessorDashboard">
                            <CardAula
                                disciplina='Matemática'
                                alunosCadastrados='3'
                                maxAlunos='6'
                                assunto='Gaussianas'
                                data='14/09/2021'
                                nomeProfessor='Maruse'
                                urlFotoProfessor='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFCdBM4y9bciDDNPr1vCnxg6j3ZUw3YfwHt3YG2_ucqg&s'
                            />
                            <CardAula
                                disciplina='Matemática'
                                alunosCadastrados='3'
                                maxAlunos='6'
                                assunto='Gaussianas'
                                data='14/09/2021'
                                nomeProfessor='Maruse'
                                urlFotoProfessor='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFCdBM4y9bciDDNPr1vCnxg6j3ZUw3YfwHt3YG2_ucqg&s'
                            />
                            <CardAula
                                disciplina='Matemática'
                                alunosCadastrados='3'
                                maxAlunos='6'
                                assunto='Gaussianas'
                                data='14/09/2021'
                                nomeProfessor='Maruse'
                                urlFotoProfessor='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFCdBM4y9bciDDNPr1vCnxg6j3ZUw3YfwHt3YG2_ucqg&s'
                            />
                            <CardAula
                                disciplina='Matemática'
                                alunosCadastrados='3'
                                maxAlunos='6'
                                assunto='Gaussianas'
                                data='14/09/2021'
                                nomeProfessor='Maruse'
                                urlFotoProfessor='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFCdBM4y9bciDDNPr1vCnxg6j3ZUw3YfwHt3YG2_ucqg&s'
                            />
                            <CardAula
                                disciplina='Matemática'
                                alunosCadastrados='3'
                                maxAlunos='6'
                                assunto='Gaussianas'
                                data='14/09/2021'
                                nomeProfessor='Maruse'
                                urlFotoProfessor='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFCdBM4y9bciDDNPr1vCnxg6j3ZUw3YfwHt3YG2_ucqg&s'
                            />
                            <CardAula
                                disciplina='Matemática'
                                alunosCadastrados='3'
                                maxAlunos='6'
                                assunto='Gaussianas'
                                data='14/09/2021'
                                nomeProfessor='Maruse'
                                urlFotoProfessor='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFCdBM4y9bciDDNPr1vCnxg6j3ZUw3YfwHt3YG2_ucqg&s'
                            />
                            <CardAula
                                disciplina='Matemática'
                                alunosCadastrados='3'
                                maxAlunos='6'
                                assunto='Gaussianas'
                                data='14/09/2021'
                                nomeProfessor='Maruse'
                                urlFotoProfessor='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFCdBM4y9bciDDNPr1vCnxg6j3ZUw3YfwHt3YG2_ucqg&s'
                            />
                            <CardAula
                                disciplina='Matemática'
                                alunosCadastrados='3'
                                maxAlunos='6'
                                assunto='Gaussianas'
                                data='14/09/2021'
                                nomeProfessor='Maruse'
                                urlFotoProfessor='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFCdBM4y9bciDDNPr1vCnxg6j3ZUw3YfwHt3YG2_ucqg&s'
                            />
                            <CardAula
                                disciplina='Matemática'
                                alunosCadastrados='3'
                                maxAlunos='6'
                                assunto='Gaussianas'
                                data='14/09/2021'
                                nomeProfessor='Maruse'
                                urlFotoProfessor='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFCdBM4y9bciDDNPr1vCnxg6j3ZUw3YfwHt3YG2_ucqg&s'
                            />
                            <CardAula
                                disciplina='Matemática'
                                alunosCadastrados='3'
                                maxAlunos='6'
                                assunto='Gaussianas'
                                data='14/09/2021'
                                nomeProfessor='Maruse'
                                urlFotoProfessor='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFCdBM4y9bciDDNPr1vCnxg6j3ZUw3YfwHt3YG2_ucqg&s'
                            />
                        </div>
                    </div>
                    <div className="boxProfessorDashboard">
                        <h1>Aulas Marcadas</h1>
                        <div className="contentListProfessorDashboard">
                            <CardAula
                                disciplina='Matemática'
                                alunosCadastrados='3'
                                maxAlunos='6'
                                assunto='Gaussianas'
                                data='14/09/2021'
                                nomeProfessor='Maruse'
                                urlFotoProfessor='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFCdBM4y9bciDDNPr1vCnxg6j3ZUw3YfwHt3YG2_ucqg&s'
                            />
                            <CardAula
                                disciplina='Matemática'
                                alunosCadastrados='3'
                                maxAlunos='6'
                                assunto='Gaussianas'
                                data='14/09/2021'
                                nomeProfessor='Maruse'
                                urlFotoProfessor='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFCdBM4y9bciDDNPr1vCnxg6j3ZUw3YfwHt3YG2_ucqg&s'
                            />
                            <CardAula
                                disciplina='Matemática'
                                alunosCadastrados='3'
                                maxAlunos='6'
                                assunto='Gaussianas'
                                data='14/09/2021'
                                nomeProfessor='Maruse'
                                urlFotoProfessor='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFCdBM4y9bciDDNPr1vCnxg6j3ZUw3YfwHt3YG2_ucqg&s'
                            />
                            <CardAula
                                disciplina='Matemática'
                                alunosCadastrados='3'
                                maxAlunos='6'
                                assunto='Gaussianas'
                                data='14/09/2021'
                                nomeProfessor='Maruse'
                                urlFotoProfessor='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFCdBM4y9bciDDNPr1vCnxg6j3ZUw3YfwHt3YG2_ucqg&s'
                            />
                            <CardAula
                                disciplina='Matemática'
                                alunosCadastrados='3'
                                maxAlunos='6'
                                assunto='Gaussianas'
                                data='14/09/2021'
                                nomeProfessor='Maruse'
                                urlFotoProfessor='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFCdBM4y9bciDDNPr1vCnxg6j3ZUw3YfwHt3YG2_ucqg&s'
                            />
                            <CardAula
                                disciplina='Matemática'
                                alunosCadastrados='3'
                                maxAlunos='6'
                                assunto='Gaussianas'
                                data='14/09/2021'
                                nomeProfessor='Maruse'
                                urlFotoProfessor='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFCdBM4y9bciDDNPr1vCnxg6j3ZUw3YfwHt3YG2_ucqg&s'
                            />
                            <CardAula
                                disciplina='Matemática'
                                alunosCadastrados='3'
                                maxAlunos='6'
                                assunto='Gaussianas'
                                data='14/09/2021'
                                nomeProfessor='Maruse'
                                urlFotoProfessor='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFCdBM4y9bciDDNPr1vCnxg6j3ZUw3YfwHt3YG2_ucqg&s'
                            />
                            <CardAula
                                disciplina='Matemática'
                                alunosCadastrados='3'
                                maxAlunos='6'
                                assunto='Gaussianas'
                                data='14/09/2021'
                                nomeProfessor='Maruse'
                                urlFotoProfessor='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFCdBM4y9bciDDNPr1vCnxg6j3ZUw3YfwHt3YG2_ucqg&s'
                            />
                            <CardAula
                                disciplina='Matemática'
                                alunosCadastrados='3'
                                maxAlunos='6'
                                assunto='Gaussianas'
                                data='14/09/2021'
                                nomeProfessor='Maruse'
                                urlFotoProfessor='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFCdBM4y9bciDDNPr1vCnxg6j3ZUw3YfwHt3YG2_ucqg&s'
                            />
                            <CardAula
                                disciplina='Matemática'
                                alunosCadastrados='3'
                                maxAlunos='6'
                                assunto='Gaussianas'
                                data='14/09/2021'
                                nomeProfessor='Maruse'
                                urlFotoProfessor='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFCdBM4y9bciDDNPr1vCnxg6j3ZUw3YfwHt3YG2_ucqg&s'
                            />
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}

export default ProfessorDashBoard;